### ISSUE TITLE
Base58Btc encoded byte array or zeros causes StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by filip26** [multiformats/java-multibase#20]
```java
Multibase.decode("z111111111111111111111111111111111");
```
throws this:
```java
java.lang.StringIndexOutOfBoundsException: String index out of range: 33
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:1515)
	at io.ipfs.multibase.Base58.decode(Base58.java:68)
	at io.ipfs.multibase.Multibase.decode(Multibase.java:55)
...
```

**Comment by BigLep** [comment]
@ianopolous : are you able to take this?

**Comment by ianopolous** [comment]
I can't reproduce this on current master. It seems to work fine.
